// Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.ChainalysisProxy.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.ChainalysisProxy;
    using Lykke.Service.ChainalysisProxy.AutorestClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class IExposureDetails
    {
        /// <summary>
        /// Initializes a new instance of the IExposureDetails class.
        /// </summary>
        public IExposureDetails()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IExposureDetails class.
        /// </summary>
        public IExposureDetails(long sentIndirectExposure, long sentDirectExposure, long receivedIndirectExposure, long receivedDirectExposure, string category = default(string))
        {
            Category = category;
            SentIndirectExposure = sentIndirectExposure;
            SentDirectExposure = sentDirectExposure;
            ReceivedIndirectExposure = receivedIndirectExposure;
            ReceivedDirectExposure = receivedDirectExposure;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Category")]
        public string Category { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SentIndirectExposure")]
        public long SentIndirectExposure { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SentDirectExposure")]
        public long SentDirectExposure { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ReceivedIndirectExposure")]
        public long ReceivedIndirectExposure { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ReceivedDirectExposure")]
        public long ReceivedDirectExposure { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
