// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ChainalysisProxy.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class IExposureDetails
    {
        /// <summary>
        /// Initializes a new instance of the IExposureDetails class.
        /// </summary>
        public IExposureDetails()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IExposureDetails class.
        /// </summary>
        public IExposureDetails(int sentIndirectExposure, int sentDirectExposure, int receivedIndirectExposure, int receivedDirectExposure, string category = default(string))
        {
            Category = category;
            SentIndirectExposure = sentIndirectExposure;
            SentDirectExposure = sentDirectExposure;
            ReceivedIndirectExposure = receivedIndirectExposure;
            ReceivedDirectExposure = receivedDirectExposure;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Category")]
        public string Category { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SentIndirectExposure")]
        public int SentIndirectExposure { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SentDirectExposure")]
        public int SentDirectExposure { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ReceivedIndirectExposure")]
        public int ReceivedIndirectExposure { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ReceivedDirectExposure")]
        public int ReceivedDirectExposure { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
