// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ChainalysisProxy.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ITransactionStatus
    {
        /// <summary>
        /// Initializes a new instance of the ITransactionStatus class.
        /// </summary>
        public ITransactionStatus()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ITransactionStatus class.
        /// </summary>
        /// <param name="chainalysisRiskScore">Possible values include: 'Red',
        /// 'Amber', 'Green'</param>
        public ITransactionStatus(int outputNumber, double transactionAmount, RiskScore chainalysisRiskScore, string clientId = default(string), string transactionHash = default(string), string chainalysisName = default(string), string chainalysisCategory = default(string), string walletAddress = default(string))
        {
            ClientId = clientId;
            TransactionHash = transactionHash;
            OutputNumber = outputNumber;
            TransactionAmount = transactionAmount;
            ChainalysisName = chainalysisName;
            ChainalysisRiskScore = chainalysisRiskScore;
            ChainalysisCategory = chainalysisCategory;
            WalletAddress = walletAddress;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TransactionHash")]
        public string TransactionHash { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OutputNumber")]
        public int OutputNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TransactionAmount")]
        public double TransactionAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChainalysisName")]
        public string ChainalysisName { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Red', 'Amber', 'Green'
        /// </summary>
        [JsonProperty(PropertyName = "ChainalysisRiskScore")]
        public RiskScore ChainalysisRiskScore { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChainalysisCategory")]
        public string ChainalysisCategory { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WalletAddress")]
        public string WalletAddress { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
