// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ChainalysisProxy.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class IUserData
    {
        /// <summary>
        /// Initializes a new instance of the IUserData class.
        /// </summary>
        public IUserData()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IUserData class.
        /// </summary>
        public IUserData(int lastActivity, int scoreUpdatedDate, string userId = default(string), string score = default(string))
        {
            UserId = userId;
            LastActivity = lastActivity;
            Score = score;
            ScoreUpdatedDate = scoreUpdatedDate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userId")]
        public string UserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastActivity")]
        public int LastActivity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "score")]
        public string Score { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "scoreUpdatedDate")]
        public int ScoreUpdatedDate { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
