// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ChainalysisProxy.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class IUserInfo
    {
        /// <summary>
        /// Initializes a new instance of the IUserInfo class.
        /// </summary>
        public IUserInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IUserInfo class.
        /// </summary>
        public IUserInfo(int? total = default(int?), int? limit = default(int?), int? offset = default(int?), IList<IUserData> data = default(IList<IUserData>))
        {
            Total = total;
            Limit = limit;
            Offset = offset;
            Data = data;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "total")]
        public int? Total { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "limit")]
        public int? Limit { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "offset")]
        public int? Offset { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "data")]
        public IList<IUserData> Data { get; set; }

    }
}
