// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ChainalysisProxy.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class IUserExplosureDetails
    {
        /// <summary>
        /// Initializes a new instance of the IUserExplosureDetails class.
        /// </summary>
        public IUserExplosureDetails()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IUserExplosureDetails class.
        /// </summary>
        public IUserExplosureDetails(int sentIndirectExposure, int sentDirectExposure, int receivedIndirectExposure, int receivedDirectExposure, string category = default(string))
        {
            Category = category;
            SentIndirectExposure = sentIndirectExposure;
            SentDirectExposure = sentDirectExposure;
            ReceivedIndirectExposure = receivedIndirectExposure;
            ReceivedDirectExposure = receivedDirectExposure;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "category")]
        public string Category { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sentIndirectExposure")]
        public int SentIndirectExposure { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sentDirectExposure")]
        public int SentDirectExposure { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "receivedIndirectExposure")]
        public int ReceivedIndirectExposure { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "receivedDirectExposure")]
        public int ReceivedDirectExposure { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
