// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ChainalysisProxy.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class IWithdrawAddressInfo
    {
        /// <summary>
        /// Initializes a new instance of the IWithdrawAddressInfo class.
        /// </summary>
        public IWithdrawAddressInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IWithdrawAddressInfo class.
        /// </summary>
        public IWithdrawAddressInfo(string name = default(string), string category = default(string), string score = default(string), string address = default(string))
        {
            Name = name;
            Category = category;
            Score = score;
            Address = address;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "category")]
        public string Category { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "score")]
        public string Score { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address")]
        public string Address { get; set; }

    }
}
