// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ChainalysisProxy.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NewWalletModel
    {
        /// <summary>
        /// Initializes a new instance of the NewWalletModel class.
        /// </summary>
        public NewWalletModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NewWalletModel class.
        /// </summary>
        /// <param name="walletType">Possible values include: 'Deposit',
        /// 'Withdrawal'</param>
        public NewWalletModel(WalletType walletType, string address = default(string))
        {
            Address = address;
            WalletType = walletType;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Address")]
        public string Address { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Deposit', 'Withdrawal'
        /// </summary>
        [JsonProperty(PropertyName = "WalletType")]
        public WalletType WalletType { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
