// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ChainalysisProxy.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for RiskScore.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum RiskScore
    {
        [EnumMember(Value = "red")]
        Red,
        [EnumMember(Value = "amber")]
        Amber,
        [EnumMember(Value = "green")]
        Green
    }
    internal static class RiskScoreEnumExtension
    {
        internal static string ToSerializedValue(this RiskScore? value)
        {
            return value == null ? null : ((RiskScore)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this RiskScore value)
        {
            switch( value )
            {
                case RiskScore.Red:
                    return "red";
                case RiskScore.Amber:
                    return "amber";
                case RiskScore.Green:
                    return "green";
            }
            return null;
        }

        internal static RiskScore? ParseRiskScore(this string value)
        {
            switch( value )
            {
                case "red":
                    return RiskScore.Red;
                case "amber":
                    return RiskScore.Amber;
                case "green":
                    return RiskScore.Green;
            }
            return null;
        }
    }
}
