// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ChainalysisProxy.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for TransactionType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TransactionType
    {
        [EnumMember(Value = "Reseived")]
        Reseived,
        [EnumMember(Value = "Sent")]
        Sent
    }
    internal static class TransactionTypeEnumExtension
    {
        internal static string ToSerializedValue(this TransactionType? value)
        {
            return value == null ? null : ((TransactionType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this TransactionType value)
        {
            switch( value )
            {
                case TransactionType.Reseived:
                    return "Reseived";
                case TransactionType.Sent:
                    return "Sent";
            }
            return null;
        }

        internal static TransactionType? ParseTransactionType(this string value)
        {
            switch( value )
            {
                case "Reseived":
                    return TransactionType.Reseived;
                case "Sent":
                    return TransactionType.Sent;
            }
            return null;
        }
    }
}
