// Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.ChainalysisProxy.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.ChainalysisProxy;
    using Lykke.Service.ChainalysisProxy.AutorestClient;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for TransactionType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TransactionType
    {
        [EnumMember(Value = "Reseived")]
        Reseived,
        [EnumMember(Value = "Sent")]
        Sent
    }
}
