// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ChainalysisProxy.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TransactionStatusResult
    {
        /// <summary>
        /// Initializes a new instance of the TransactionStatusResult class.
        /// </summary>
        public TransactionStatusResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TransactionStatusResult class.
        /// </summary>
        public TransactionStatusResult(IList<ITransactionStatus> transactions = default(IList<ITransactionStatus>))
        {
            Transactions = transactions;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Transactions")]
        public IList<ITransactionStatus> Transactions { get; set; }

    }
}
