// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ChainalysisProxy.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for WalletType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum WalletType
    {
        [EnumMember(Value = "Deposit")]
        Deposit,
        [EnumMember(Value = "Withdrawal")]
        Withdrawal
    }
    internal static class WalletTypeEnumExtension
    {
        internal static string ToSerializedValue(this WalletType? value)
        {
            return value == null ? null : ((WalletType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this WalletType value)
        {
            switch( value )
            {
                case WalletType.Deposit:
                    return "Deposit";
                case WalletType.Withdrawal:
                    return "Withdrawal";
            }
            return null;
        }

        internal static WalletType? ParseWalletType(this string value)
        {
            switch( value )
            {
                case "Deposit":
                    return WalletType.Deposit;
                case "Withdrawal":
                    return WalletType.Withdrawal;
            }
            return null;
        }
    }
}
